CXX = clang++
CXXFLAGS = -std=c++14 -Wall -Wextra -pedantic -O2

loginAndRegistration: loginAndRegistration.cpp
	$(CXX) $(CXXFLAGS) -o loginAndRegistration loginAndRegistration.cpp

clean:
	rm -f loginAndRegistration
